# Generated by Django 5.0.6 on 2024-12-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_editorial_ciudad_alter_editorial_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='premios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
